### ISSUE TITLE
[Question] - Why require rainbow brackets?

### ISSUE THREAD

**Issue by ricardoboss** [dinbtechit/vscode-theme#100]
## Question:

Why does this plugin require another plugin - rainbow brackets? I don't really use VS Code, is rainbow brackets a feature of the default theme?

I mean sure, I can disable rainbow brackets in the settings, but the plugin is enabled nonetheless and consumes RAM. I don't want it and I don't need it.

## Platform & Language Details: 

Rider (C#) & Android Studio (Dart)

**Comment by majoker** [comment]
+1

**Comment by ricardoboss** [comment]
Can't disable the plugin without disabling VS Code 
![image](https://github.com/dinbtechit/vscode-theme/assets/6266356/c30a7fad-1089-43ca-b0fa-8c7fb7c2052d)

**Comment by kiraleos** [comment]
This is indeed a very weird decision. Please remove this new dependency!

**Comment by dinbtechit** [comment]
Thank you for reporting this issue. It makes sense. I can remove this.
