### ISSUE TITLE
[Bug] - How to remove black background in Jupyter

### ISSUE THREAD

**Issue by lrstolk** [dinbtechit/vscode-theme#139]
## Question:
With the dark and modern dark theme I get these black backgrounds. Currently only happens in jupyter files. 
How do I remove them? 
![image](https://github.com/dinbtechit/vscode-theme/assets/35999180/bbd20224-8560-40f2-9a20-337582d26e70)

## Platform & Language Details: 
Python 
PyCharm
  ```
PyCharm 2023.2.1 (Professional Edition)
Build #PY-232.9559.58, built on August 22, 2023
Licensed to Lorenzo Stolk
Subscription is active until April 8, 2024.
For educational use only.
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    editor.focus.mode.color.light=737374
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=737374

Non-Bundled Plugins:
    dracula-vscode (1.0.2)
    com.samdark.intellij-visual-studio-code-dark-plus (2.8)
    com.mallowigi (93.1.0)
    monokai-pro (1.10)
    com.github.dinbtechit.vscodetheme (1.10.3)
    com.chrisrm.idea.MaterialThemeUI (8.12.2)
  ```

**Comment by dinbtechit** [comment]
interesting. I am not a python developer. Are you able to provide a sample github repo that I can use for testing?

**Comment by lrstolk** [comment]
> interesting. I am not a python developer. Are you able to provide a sample github repo that I can use for testing?
https://github.com/lrstolk/temp 
U can download something like PyCharm, create an evironment and install the packages.

**Comment by lrstolk** [comment]
> > interesting. I am not a python developer. Are you able to provide a sample github repo that I can use for testing?
> 
> https://github.com/lrstolk/temp U can download something like PyCharm, create an evironment and install the packages.

Just found it it is also on the light modern. 
![image](https://github.com/dinbtechit/vscode-theme/assets/35999180/6fde627e-08c8-41bf-85d7-fafea44ebed3)

**Comment by dinbtechit** [comment]
A temp fix has been added in  [v1.10.4](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.10.4)

**Comment by lrstolk** [comment]
df.**head**(10)
df['year'].**apply**(convert_int)
J_history.append(**J**(X, y, theta))
X.**transpose**().**dot**(hyp - y)
np.**sum**(square_err)
plt.**ylabel**('0')
pd.**read_csv**()

**Comment by dinbtechit** [comment]
Reopening this. I need to think of a permanent solution for this.

**Comment by dinbtechit** [comment]
sorry between personal life  and my full time job. I haven't been had a chance to get back to this. I try to get this in the next couple of days or during the Christmas holidays.

**Comment by lrstolk** [comment]
@dinbtechit how are you? 
Have you been able to take  look at this?
