### ISSUE TITLE
[Bug] - Inconsistent highlighting of Python class names

### ISSUE THREAD

**Issue by jonasmaertens** [dinbtechit/vscode-theme#161]
## Describe the bug

In VSCode, imported Classes are highlighted in green when instantiated. This higjlighting feature seems broken in the plugin, as it only works sometimes (apparently depending on the context). See screenshots attached for different highlighting behavior. The only difference in the file between the screenshots is the one empty line that i added. The class in the screenshot is imported from a local file as "from DQN_file import DQN". I tried disabling all plugings except vscode-theme, but that didn't chnage the behavior. I couldnt manage to create a file for a minimal working example, as the behavior seems really random and dependent on the context.

## Platform & Language Details 
- Language: Python
- IDE Details:  
PyCharm 2023.2.3 (Professional Edition)
Build #PY-232.10072.31, built on October 12, 2023
Licensed to Jonas Märtens
Subscription is active until October 15, 2024.
For educational use only.
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  ide.rest.api.requests.per.minute=45
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.copilot (1.3.2.3479)
  net.seesharpsoft.intellij.plugins.csv (3.2.2-232)
  izhangzhihao.rainbow.brackets (2023.3.6)
  com.github.dinbtechit.vscodetheme (1.10.6)

## Jetbrains Screenshot
![screenshot_3](https://github.com/dinbtechit/vscode-theme/assets/71458938/918f800e-e5e9-4f63-aba3-45a5011e0677)
![screenshot_2](https://github.com/dinbtechit/vscode-theme/assets/71458938/c56ec018-95ec-4504-99fb-ba3a6f0783e8)
![screenshot_1](https://github.com/dinbtechit/vscode-theme/assets/71458938/bacda544-5090-4e5d-ba17-3428ea7f246c)

## VSCode Screenshot
![screenshot_vs](https://github.com/dinbtechit/vscode-theme/assets/71458938/e3845fd5-fa7d-4be1-9d4f-9fdc1f942f7c)

**Comment by dinbtechit** [comment]
@jonasmaertens - Python highlighting is a bit experimentally glad you reported an issue. This will help us to make it better. Could you please share a sample GitHub repository that we can use for testing?

**Comment by jonasmaertens** [comment]
@dinbtechit you can use the repository I'm currently working on (my Bachelor thesis) for testing if you want. You should probably fork it as it changes a lot right now. You will find the example from my screenshots in /TASEP-Smarticles/Trainer.py in _init_model(), lines 99-100. Sometimes the highlighting works just fine. In that case try inserting blank lines or brackets or try restarting PyCharm, as the behavior seems to be different after restarting. Thanks for looking into this!
Repo is: [https://github.com/jonasmaertens/TASEP](https://github.com/jonasmaertens/TASEP)
