### ISSUE TITLE
[Bug] - Javascript constant color is inconsistent.

### ISSUE THREAD

**Issue by oooth** [dinbtechit/vscode-theme#172]
## Describe the bug

Javascript constant color is inconsistent compared to VS Code.
They look like variables and should be darker.

*Note:* When used in objects as short form (without explicitly define `{ meteo: meteo }` but rather `{ meteo }`, the constant does not have to keep its constant color because it's an object property definition. This point is good, not to be fixed.

## Platform & Language Details 
- Language: Javascript
- IDE Details:
```
function f () {
  const usedConstant = ''
  let usedVariable = ''

  const unusedConstant = usedConstant
  let unusedVariable = usedVariable

  const object = {
    usedConstant,
    usedVariable,
  }
}
```

## Jetbrains Screenshot
![JetBrainsWebStorm](https://github.com/dinbtechit/vscode-theme/assets/23332752/f1838a85-ea7e-46fe-91dd-3f28ef73b31d)

## VSCode Screenshot
![VSCode](https://github.com/dinbtechit/vscode-theme/assets/23332752/c49d7fa5-7bb8-4e12-bbe4-2542f1d40ea4)

**Comment by dinbtechit** [comment]
@oooth  - Thank you for reporting this issue.
