### ISSUE TITLE
[Bug] - in Gateway intellJidea not load color scheme

### ISSUE THREAD

**Issue by loso2255** [dinbtechit/vscode-theme#173]
## Describe the bug
when i use Gateway with IntelliJidea IDE i see different colors than when I use directly intellJidea on my pc.
i think this error is related to not load "Extra" color for any Languages, because in the menu "Editor" -> "Color Scheme" on the Gateway + IntelliJidea IDE side, i don't see "Java (Extra)" only Java 

## Platform & Language Details 
- Language: Java i think this error may extend on every Language
- IDE Details:  
JetBrains Client 2023.2.5
Build #JBC-232.10227.8, built on November 9, 2023
Runtime version: 17.0.9+7-b1000.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Controller in Remote Development (IU), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    editor.input.method.inlay=true
    ide.experimental.ui=true
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    com.intellij.plugins.eclipsekeymap (232.8660.88)
    com.github.dinbtechit.vscodetheme (1.10.7)
    com.intellij.plugins.visualstudiokeymap (232.8660.88)
    com.intellij.plugins.netbeanskeymap (232.8660.88)

**Comment by dinbtechit** [comment]
@loso2255 Thank you for reporting this bug. I'll have to check if we can even support GatewayIDEs.  Stay tuned.

**Comment by loso2255** [comment]
any news?

**Comment by loso2255** [comment]
> @loso2255 Thank you for reporting this bug. I'll have to check if we can even support GatewayIDEs. Stay tuned.

any news?

**Comment by dinbtechit** [comment]
Reopening this issue. Was closed due to inactivity but this is not fixed yet.

This is still on the road map, but JetBrains deprecated a lot of APIs which took priority over this. Hopefully, if I can one of the weekends free I can work on this.,

**Comment by loso2255** [comment]
i can wait, thanks a lot.

so i need to reopen this issue or you can set this issue as open?

**Comment by loso2255** [comment]
hi any news on this problem?
