### ISSUE TITLE
[Bug] - Font type inside code window is wrong

### ISSUE THREAD

**Issue by marcelfrank-dev** [dinbtechit/vscode-theme#181]
## Describe the bug

The font for my code is not in a code style (i.e. JetBrains mono). It's not good readable with a no-code font, so it's not really usable for me.

## Platform & Language Details 
- Language: Java/JavaScript/Typescript (all?)
- IDE Details:  
```
IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023
Licensed to Decadis AG / Marcel Frank
You have a perpetual fallback license for this version.
Subscription is active until January 9, 2025.
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  actionSystem.fix.alt.gr=false
  tests.view.node.expanding.search=false
  ide.experimental.ui=true
  typescript.service.node.arguments=--max-old-space-size=4096
Non-Bundled Plugins:
  com.google.bamboo.id (1.6.6-203)
  com.nasller.CodeGlancePro (1.7.8)
  de.netnexus.camelcaseplugin (3.0.12)
  com.github.copilot (1.4.12.4386)
  com.intellij.ideolog (222.3.1.0)
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  com.github.oowekyala.javacc (1.12.1)
  com.github.kisstkondoros.codemetrics (1.0.4)
  com.jetbrains.jax.ws (233.11799.196)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
  net.seesharpsoft.intellij.plugins.csv (3.2.3-233)
  Dart (233.11799.172)
  com.intellij.spring.osgi (233.11799.196)
  MetricsReloaded (1.12)
  com.dmarcotte.handlebars (233.11799.172)
  com.jetbrains.lang.ejs (233.11799.172)
  MavenRunHelper (4.27.1-IJ2022.2)
  Pythonid (233.11799.300)
  net.ashald.envfile (3.4.2)
  com.github.nikolaikopernik.codecomplexity (1.4.0)
  com.intellij.jira (4.7.1)
  org.jetbrains.plugins.docker.gateway (233.11799.244)
  com.jetbrains.php (233.11799.300)
  org.exbin.deltahex.intellij (0.2.9)
  com.jetbrains.php.wordPress (233.11799.300)
  io.snyk.snyk-intellij-plugin (2.6.2)
  com.github.dinbtechit.vscodetheme (1.10.9)
Kotlin: 233.11799.241-IJ
```

## Jetbrains Screenshot

![image](https://github.com/dinbtechit/vscode-theme/assets/122784386/90776080-74b7-4e5e-a24a-cfb6ea7c7f3b)

![image](https://github.com/dinbtechit/vscode-theme/assets/122784386/a1002874-8ae7-4179-8e7c-ca88bb42fa14)

**Comment by dinbtechit** [comment]
@marcelfrank-dev  - VSCode plugin does not modify the IDE fonts. 

You might want to check your -> Settings | Editor | Font -> Ensure if it set to `JetBrains Mono` font.

![image](https://github.com/dinbtechit/vscode-theme/assets/17984781/bc7fcb27-7fa6-4f2a-993e-ed3d803a2161)

**Comment by marcelfrank-dev** [comment]
Hey @dinbtechit,
thanks for the fast response!

You made my day! Finally I can use the theme again.

To be honest, I still do not understand why the font was changed there. For me it was not in Settings | Editor | Font, but in Settings | Editor | Color Scheme | Color Scheme Font.

![image](https://github.com/dinbtechit/vscode-theme/assets/122784386/15c0267d-e36f-4781-be99-7653ee38ae1a)

Thank you very much!
