### ISSUE TITLE
[Bug] - Wrong colors in the new Terminal

### ISSUE THREAD

**Issue by AleksBaikalsky** [dinbtechit/vscode-theme#187]
The new Terminal feature of the InteliJ 2024.1 platform has wrongly-looking colors. 

Suggestion is to make backgrounds of regular texts transparent, as there are a few states of the blocks and each has its own background.

E.g. in VSCode Dark Modern, in PhpStorm:
![2024-04-07_12h16_16](https://github.com/dinbtechit/vscode-theme/assets/86363353/91b7b1a4-69b3-4573-afc6-81b3fd3fe038)
![2024-04-07_12h15_46](https://github.com/dinbtechit/vscode-theme/assets/86363353/092d1f2e-eb66-4d36-9341-c16bc9c1571e)

**Comment by dinbtechit** [comment]
@AleksBaikalsky - are you able to provide some step-by-steps to reproduce this issue? I am not sure what exactly you are looking for. Cheers!
