### ISSUE TITLE
[Question] - Why is "VSCode Dark Modern" missing as "Editor color scheme"?

### ISSUE THREAD

**Issue by coding-novice** [dinbtechit/vscode-theme#191]
## Question:

I really like the plugin, since I am quite used to the VS code color scheme. I use it mainly for Jupyter Notebooks and love the black background in the cells. While my favorite color theme "VSCode Dark Modern" is available in PyCharm by using the plugin, this exact color scheme is the only missing VSCode color scheme when selecting an "Editor color scheme" in PyCharm. Is this intentional? Will it be added, or is it maybe even a bug?

## Platform & Language Details: 
- Language: Python (using Jupyter Notebooks)
- IDE Details: PyCharm

PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
Licensed to ____
Subscription is active until April 30, 2025.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2922M
Cores: 16
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.10.0)
  com.github.dinbtechit.vscodetheme (1.10.10)
  com.blai30.lotus.theme (1.11)

**Comment by dinbtechit** [comment]
Apologies for the late reply. Are you able to rephrase your question I am not sure if understand what is that you are looking for. Perhaps some screenshots would also help. Thanks
