### ISSUE TITLE
[Bug] - yield keyword not formatted

### ISSUE THREAD

**Issue by j-d-ha** [dinbtechit/vscode-theme#194]
## Describe the bug

When using this theme with PyCharm, the `yield` keyword is not formatted as a secondary keyword. 

## Jetbrains Screenshot
![image](https://github.com/dinbtechit/vscode-theme/assets/61319894/c14ea40a-538e-4f13-b592-c7f42eab661b)

## VSCode Screenshot
![image](https://github.com/dinbtechit/vscode-theme/assets/61319894/d7d80738-0a50-4e49-88c4-92a1cc500b30)

**Comment by dinbtechit** [comment]
Addressed in https://github.com/dinbtechit/vscode-theme/pull/196

**Comment by dinbtechit** [comment]
Resolved in V1.10.11
