### ISSUE TITLE
[Bug] - Weird colors on custom ZSH/iTerm theme in terminal

### ISSUE THREAD

**Issue by marcelreppi** [dinbtechit/vscode-theme#31]
## Describe the bug

There is a weird color overlay inside the Intellij terminal when I have a custom ZSH/iTerm theme defined. 
In other Intellij themes the colors are not correct as well but at least there isn't this weird overlay. 
In VSCode it looks much better and almost like the original theme in iTerm.

## Platform & Language Details (please complete the following information):
- Platform: IntelliJ
- Platform Version: 2022.2.2
- Language: Terminal (zsh)
- ZSH theme: agnoster
- iTerm theme: Dark Pastel (with some slight modifications)

## Jetbrains Screenshot
VSCode theme
![Screenshot 2022-11-07 at 11 25 21](https://user-images.githubusercontent.com/22420478/200275824-4a80009a-2485-487b-9098-15150998b279.png)

Other theme
![Screenshot 2022-11-07 at 11 34 34](https://user-images.githubusercontent.com/22420478/200276591-b5418412-3200-4fef-bc92-70a1798e5aab.png)

## VSCode Screenshot
<img width="368" alt="Screenshot 2022-11-07 at 11 33 01" src="https://user-images.githubusercontent.com/22420478/200276248-89c9c60d-5b76-46c1-b91b-ecf9fad91881.png">

## iTerm Screenshot
<img width="375" alt="Screenshot 2022-11-07 at 11 38 19" src="https://user-images.githubusercontent.com/22420478/200277403-4a2ca5b2-8027-4456-afd6-30d77463de47.png">

**Comment by dinbtechit** [comment]
Fixed in [v1.7.25](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.7.2)

**Comment by marcelreppi** [comment]
I just upgraded the plugin now to see if it's actually fixed but it still looks the same 😕

**Comment by dinbtechit** [comment]
Interesting!  The colors are showing fine on mine. 


![image](https://user-images.githubusercontent.com/17984781/200820793-ca3ea33c-27a1-4a42-9205-b847a6b42c62.png)


![image](https://user-images.githubusercontent.com/17984781/200820212-ba9a68e1-80fc-4090-b245-3621fe47141f.png)

Can you check if the <kbd>Settings</kbd> (Preferences on Mac) -> `Editor` -> `Color Scheme` -> `Console Colors` -> ANSI Colors are same as the below screen shot??

![Kapture 2022-11-09 at 07 45 52](https://user-images.githubusercontent.com/17984781/200822352-a0a799fc-412d-4069-a346-bad3a559d9d5.gif)

**Comment by dinbtechit** [comment]
Oh right. If you have modified the theme manually. Then the plugin will retain all the modifications. Happy to help!
