### ISSUE TITLE
[Feature] - chained function color

### ISSUE THREAD

**Issue by bennyk8y** [dinbtechit/vscode-theme#37]
Hi, chained function is not colored for some reason.:
![CleanShot 2022-11-28 at 15 33 21@2x](https://user-images.githubusercontent.com/106013384/204290594-5c0b5915-62ae-43f6-932f-188d9cd41e23.png)

Is there a way to achieve this coloring?

**Comment by bennyk8y** [comment]
Yes, typescript. Using WebStorm.
I see that it happens in specific cases:
<img width="639" alt="CleanShot 2022-11-28 at 16 19 09@2x" src="https://user-images.githubusercontent.com/106013384/204300455-4813467f-d1a9-41e1-8e09-749045b85d3d.png">

Now for some reason `.create` is not colored and `.toObject` as well.
Also, for some reason an imported function is not colored:
<img width="590" alt="CleanShot 2022-11-28 at 16 22 36@2x" src="https://user-images.githubusercontent.com/106013384/204301272-11433a23-7904-42e8-944d-6321423fbdef.png">

But function that imported from the project does get coloring
<img width="828" alt="CleanShot 2022-11-28 at 16 24 38@2x" src="https://user-images.githubusercontent.com/106013384/204301751-584f09f8-f251-4acf-ac46-52f7272d9c91.png">

**Comment by dinbtechit** [comment]
are you using any frameworks like react or emberjs? Or is it plain typescript? 

I know some frameworks do reset the base colors for some reason which makes it a bit trickier to apply the colors without breaking the framework's intelli-sense.

**Comment by bennyk8y** [comment]
Its backend code, plain typescript

**Comment by dinbtechit** [comment]
For some reason. I couldn't reproduce the issue. I would appreciate it if you can create a sample project to reproduce the issue.

I am pushing in some changes for Typescript in v1.7.4. However, I dont think it will address your issue. But in the long term, I will need to rethink a solution for Typescript and JavaScript highlighting. Jetbrains base syntax highlighting is a bit finicky. It reset the custom colors for some reason.

**Comment by dinbtechit** [comment]
Unable to reproduce the issue. I tried it on react, angular, and plain typescript projects. I had no issues with the chain functions. 

Please feel free to reopen this issue if the problem persists. Make sure to include a sample git project. Thank you.
