### ISSUE TITLE
[Feature] - Enhance C++ theme based on official VSCode theme for C++

### ISSUE THREAD

**Issue by ApsarasX** [dinbtechit/vscode-theme#4]
**Describe the solution you'd like**
VSCode has provided office theme for C++ in [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools/blob/main/Themes/themes/cpptools_dark_vs.json).

Maybe you can refer to the theme here to enhance the C++ theme in the current plugin.

**Feature for Platform & Language:**
 - Platform: CLion
 - Platform Version: 2022.1.2
 - Language: C++

**Comment by dinbtechit** [comment]
I'll see what I can do over the weekend.  Stay tuned.

**Comment by dinbtechit** [comment]
Resolved in [v1.5.0](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.5.0)

**Comment by ApsarasX** [comment]
> Resolved in [v1.5.0](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.5.0)

v1.5.0 has not yet appeared in the JetBrains Marketplace.
