### ISSUE TITLE
[bug] - 希望加深控制台的背景色

### ISSUE THREAD

**Issue by WangJincheng4869** [dinbtechit/vscode-theme#5]
现在的背景色是灰色，与日志文字颜色差异较小，查看起来存在视觉冲突。
![image](https://user-images.githubusercontent.com/41162158/174280424-fb10e5da-1fe9-4dc6-ac46-37b4e3555ffc.png)
可以考虑一下加深背景色，就像vscode类似，这样文字与背景颜色差距较大，看起来会更加清晰
![image](https://user-images.githubusercontent.com/41162158/174280636-13b3bf42-2838-400a-bfeb-0d299fe1ce52.png)

**Comment by dinbtechit** [comment]
Fixed in  [1.5.0](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.5.0)
