### ISSUE TITLE
[Feature] - Syntax highlighting for shell scripts

### ISSUE THREAD

**Issue by gtaylor1981** [dinbtechit/vscode-theme#55]
Please add syntax highlighting for bash/shell scripts if possible.
It already looks fairly good, but a few things are inconsistent with VS Code.

For comparison:

VSCode:
![image](https://user-images.githubusercontent.com/20638908/236391876-ba921a5b-d641-4dba-8dc8-83ec398ab861.png)

IntelliJ with VSCode Theme (1.7.8)
![image](https://user-images.githubusercontent.com/20638908/236391905-8d234351-e716-4d5a-8591-f2087f5795be.png)

**Comment by dinbtechit** [comment]
Thank you for logging this issue. I think we should be able to fix this. I'll take a look at it during the weekend!

**Comment by dinbtechit** [comment]
Fixed in [v1.7.9](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.7.9)

The syntax highlight should be better than VSCode because of additional intelli sense.

![image](https://user-images.githubusercontent.com/17984781/236651808-ab8995ce-9fcb-4c55-88b7-ec0dda8148ba.png)
