### ISSUE TITLE
[Feature] - Java注解类与普通类没有颜色区分

### ISSUE THREAD

**Issue by WangJincheng4869** [dinbtechit/vscode-theme#6]
如下图：
![image](https://user-images.githubusercontent.com/41162158/174534375-fde92525-5182-4cc0-a2f7-9a282a5a2c2f.png)
原始主题会有明显的区别，如下图：
![image](https://user-images.githubusercontent.com/41162158/174534486-96555079-3567-43c9-8cd5-6a673cda008d.png)
希望注解类可以特殊处理，添加独立的颜色

**Comment by dinbtechit** [comment]
The goal of this plugin is to closely mimic VSCode dark theme. Currently, VSCode uses the same color for Class names and annotations.  But I am open to making this change if I get at least 500 likes for this idea. 

For now, I am closing this ticket as **won't fix**. But if more people request this feature I'll consider implementing it.

**Comment by dinbtechit** [comment]
The goal of this plugin is to closely mimic VSCode dark theme. Currently, VSCode uses the same color for Class names and annotations. But I am open to making this change if I get at least 500 likes for this idea.

For now, I am closing this ticket as won't fix. But if more people request this feature I'll consider implementing it.
