### ISSUE TITLE
VSCode Light+ Theme 🌞 

### ISSUE THREAD

**Issue by amstiel** [dinbtechit/vscode-theme#66]
Hi. Do you have any plans for Light+ variant? 🌞 
I'd like to help, determine color palette, etc.

![image](https://github.com/dinbtechit/vscode-theme/assets/9428948/b9b1ad36-592a-494c-83e9-b20c7c593515)

**Comment by dinbtechit** [comment]
Hello @amstiel, I have received multiple requests for the light variant, but unfortunately, my bandwidth is currently very limited. Nonetheless, I am grateful for your eagerness to assist. Please feel free to submit a PR for this. Thank you. 🙌🙌

**Comment by amstiel** [comment]
@dinbtechit Can you please assign this issue on me?

**Comment by dinbtechit** [comment]
@amstiel - How are you making out with this? I have some cycles to pick this up. If you haven't started this already. Cheers!

**Comment by amstiel** [comment]
@dinbtechit 
Sorry, I didn't have time at all. 😞 Haven't started porting yet.

**Comment by amstiel** [comment]
So, started porting 😄 

Got all colors from [light_vs](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/light_vs.json) and [light_plus ](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/light_plus.json). You can see them in [Figma file](https://www.figma.com/file/JBj2JRmWQFbncoxTsWQRo2/VSCode-Theme?type=design&node-id=0%3A1&mode=design&t=fvH4bQGIJQm5hulG-1). I'm planning to use JB Default Light theme for (new) UI and VSCode Light for syntax highlighting.

![image](https://github.com/dinbtechit/vscode-theme/assets/9428948/6cef0084-cfc7-421a-adf9-234863d2f93c)

**Comment by dinbtechit** [comment]
@amstiel  Excellent - you can use this python tool to convert vscode theme to intellij theme. However, I can't remember if this would also convert the code styles as well. But worth giving it a shot.

https://github.com/JetBrains/colorSchemeTool

**Comment by dinbtechit** [comment]
Created the initial version of VSCode Light Theme in [v.1.9.0](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.9.0)

**Comment by aegena** [comment]
icon can_t_see_clearly

**Comment by dinbtechit** [comment]
@aegena - Can please you create a separate ticket for that?

**Comment by dinbtechit** [comment]
Closing this ticket. As we now have a initial version of the light theme. I know its not perfect may not work for all programming languages. But let's open separate tickets for each issue. 

Thank you @amstiel for logging this issue and providing all the valuable information! Cheers
