### ISSUE TITLE
[Bug] - Dark Modern's inactive selection background color wrong

### ISSUE THREAD

**Issue by robertg042** [dinbtechit/vscode-theme#67]
## Describe the bug

Inactive selection background color (#555657) in Dark Modern theme does not correspond to one used in VS Code (#37373d). It also makes it harder to read light colored text.

## Jetbrains Screenshot
Current color:
![ij_original](https://github.com/dinbtechit/vscode-theme/assets/16643843/a316c46c-75c6-439c-8242-970e5a22ddd4)

Changed to #37373d:
![ij_fixed](https://github.com/dinbtechit/vscode-theme/assets/16643843/c3ce7977-ed47-4869-a911-2164957495b8)

## VSCode Screenshot
![vscode](https://github.com/dinbtechit/vscode-theme/assets/16643843/a666d3e7-be9f-4bb4-9129-7559ec7c93e6)

**Comment by robertg042** [comment]
I think it may be necessary to change all three properties: `selectionInactiveBackground`, `selectionBackgroundInactive` and `lightSelectionInactiveBackground`

**Comment by dinbtechit** [comment]
@robertg042 - Thank you for reporting this issue. 🙌  Can you submit a PR for this? If not, I would have to pick this up when I have some time. Cheers!

**Comment by robertg042** [comment]
@dinbtechit Sure, as soon as I can

**Comment by dinbtechit** [comment]
Fixed in https://github.com/dinbtechit/vscode-theme/releases/tag/v1.8.1

Thanks to @robertg042 !!!
