### ISSUE TITLE
[Bug] - Last Updated broke my color scheme 

### ISSUE THREAD

**Issue by johannstark** [dinbtechit/vscode-theme#79]
## Describe the bug

Greetings!

Look somehow the last update broke my color scheme, somewhere in the configs is changing my highlighting.
And even in the config preview looks right but the editor looks different and I cant find which setting is overwritting my setup.

I have tailor my color scheme to look like the Atom One Dark theme but with the VSCode Dark Modern background

How it should be:
<img width="565" alt="image" src="https://github.com/dinbtechit/vscode-theme/assets/17615630/a8519e6a-974c-42f8-a9ae-855e5f8bad81">

How it looks right now:
<img width="552" alt="image" src="https://github.com/dinbtechit/vscode-theme/assets/17615630/7ae8694d-74fd-4c45-a4bd-dc4faa441f64">

## Platform & Language Details 
- Language: python
- IDE Details:  
  ```
  PyCharm 2023.1.3 (Professional Edition)
Build #PY-231.9161.41, built on June 20, 2023
Licensed to Hunty / Juan Esteban Camacho
Subscription is active until July 9, 2023.
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1264M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    color.scheme.Atom One Dark (0.4)
    hu.aradipatrik.onedarknative (1.5)
    com.github.ioannuwu.inline (1.1.1)
    co.anbora.labs.ngrok (1.3.8)
    com.github.copilot (1.2.9.2684)
    mobi.hsz.idea.gitignore (4.5.1)
    zielu.gittoolbox (500.0.10+213)
    com.github.dinbtechit.vscodetheme (1.8.3)
    ru.adelf.idea.dotenv (2023.1)
    ru.meanmail.plugin.requirements (2022.4.1)
    izhangzhihao.rainbow.brackets (2023.2.11)
    com.google.gct.core (23.6.3-api-version-222)
  ```

**Comment by dinbtechit** [comment]
Right now changing the color scheme through settings is not fully supported.

The import statement use the same color as the class Names.  Maybe we can split them out.

**Comment by dinbtechit** [comment]
Fixed in https://github.com/dinbtechit/vscode-theme/releases/tag/v1.8.5 (Part 2)
