### ISSUE TITLE
[Bug] - Used types look like unused.

### ISSUE THREAD

**Issue by ShiftWatchOut** [dinbtechit/vscode-theme#85]
## Describe the bug

Both import statement and the place they are used, types have a lower opacity or lighter color whatever. This kind of appearance indicates one word haven't been used in VSC, which is not IDEA means in other theme.

## Platform & Language Details 
- Language: Java.
- IDE Details:  
  ```
  IntelliJ IDEA 2023.1.4 (Community Edition)
  Build #IC-231.9225.16, built on July 12, 2023
  Runtime version: 17.0.7+10-b829.16 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  Windows 11.0
  GC: G1 Young Generation, G1 Old Generation
  Memory: 1024M
  Cores: 6
  Non-Bundled Plugins:
      com.github.dinbtechit.vscodetheme (1.8.5)
  
  Kotlin: 231-1.8.21-IJ9225.16
  ```

## Jetbrains Screenshot
![image](https://github.com/dinbtechit/vscode-theme/assets/23012269/603a3b95-c9ad-45cb-8d98-f146765601c9)
Compare with the default theme of IDEA.
![image](https://github.com/dinbtechit/vscode-theme/assets/23012269/5aad2a59-cdcb-4fbe-80e2-41504fb650ef)

## VSCode Screenshot
![image](https://github.com/dinbtechit/vscode-theme/assets/23012269/fff4a33f-70bd-478a-b5e0-3d3af9647dec)

**Comment by dinbtechit** [comment]
Thanks for reporting a bug. Intellij has an option to use different color for interfaces. I thought it would be better to differentiate them from the classes. Do you have any suggestions on what color we could use for interfaces?

**Comment by ShiftWatchOut** [comment]
Maybe you could use the same strategy you're using on static methods of class, give them deeper color than this green.

**Comment by ShiftWatchOut** [comment]
> Thanks for reporting a bug. Intellij has an option to use different color for interfaces. I thought it would be better to differentiate them from the classes. Do you have any suggestions on what color we could use for interfaces?

I'm just starting using IDEA in order to learn backend development, your theme help me distinguish a lot of things. According to this reply, I found where I could configure interface's color, and I noticed that you are actually using a deeper color🥲. It's the dark background makes it so weird.

**Comment by dinbtechit** [comment]
ok I'll make it the same color as classes. Hopefully, that will look better.

**Comment by ShiftWatchOut** [comment]
Deeper is not the way, maybe we go brighter?
![image](https://github.com/dinbtechit/vscode-theme/assets/23012269/dddfd8c5-4f9e-463a-b106-c978b6245318)
