### ISSUE TITLE
[Bug] - operator and @decorator colors Python

### ISSUE THREAD

**Issue by hect0x7** [dinbtechit/vscode-theme#91]
## Describe the bug

1. operator (+ - * / ** // == > <) color should be white but golden
2. `@` color should be golden when applying to decorator but green

## Platform & Language Details 
- Language: Python
- IDE Details:  
  ```
  PyCharm 2023.2 (Professional Edition)
  Build #PY-232.8660.197, built on July 26, 2023
  ```

## Jetbrains Screenshot
![Snipaste_2023-08-08_09-54-24](https://github.com/dinbtechit/vscode-theme/assets/93357912/f17b7d79-f6db-423f-9566-cf1bd5e58a03)

## VSCode Screenshot
![Snipaste_2023-08-08_09-55-01](https://github.com/dinbtechit/vscode-theme/assets/93357912/de14db20-cae9-4f4d-9564-a6a93e404933)

## Additional context/Logs
code above:
```python
def cache(func):
    pass


@cache
def a(i):
    if i % 2 == 0:
        raise AssertionError
    return 1

```

**Comment by dinbtechit** [comment]
Thank you for reporting this bug! Should be easy to fix this.

**Comment by dinbtechit** [comment]
Fixed in [v.1.9.1](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.9.1)
