### ISSUE TITLE
[Question] - Turning off the ligatures

### ISSUE THREAD

**Issue by danieltomasz** [dinbtechit/vscode-theme#92]
Thanks for nice plugin - I just switched from VSCode to  try DataSpell/Pycharm.

With the plugin and Visual Studio Light  theme enable I see ligatures in my code `!=` or `->`, even if I don't have them turned on in VSCode; how can I turn it with your plugin? 
  
I was unable to find the settings of the plugin within editor.
Build #DS-232.8660.202, built on July 27, 2023

**Comment by dinbtechit** [comment]
Thank you for your kind words!

A couple of things: 

1. Firstly, this plugin does not offer a light theme yet. I'm assuming you have installed another plugin for the Visual Studio light theme? On a side note - Alex is currently working to create a light theme for #66 
2. Secondly.. this plugin does not modify the ligatures by any means.. I'm not sure if that is being enabled by some other plugin you may have installed. I would check `settings` -> `Editor` -> `Font` to ensure that the option is not enabled there. Other than that, I can't think of anything that would cause that.


https://github.com/dinbtechit/vscode-theme/assets/17984781/1ec65664-3d87-4184-8aa5-e259a69b0bf1

**Comment by danieltomasz** [comment]
Thank you for help!
 it was my fault, there was indeed another plugin for light theme I forgot I installed, and the  this plugin latest  updated correlated with me spotting ligatures  :) The light theme will be super useful! :)
